# Generated by Django 5.0.4 on 2024-10-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='voter_name_hashed',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
